// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhBNZ-yt9npIdG9hW6X5Z8R6XRcjqTUxc',
    authDomain: 'pd-app-f2656.firebaseapp.com',
    projectId: 'pd-app-f2656',
    storageBucket: 'pd-app-f2656.firebasestorage.app',
    messagingSenderId: '208818382983',
    appId: '1:208818382983:web:69c177f50a804188523022',
    measurementId: 'G-NK0QRX6T3J',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhBNZ-yt9npIdG9hW6X5Z8R6XRcjqTUxc',
    authDomain: 'pd-app-f2656.firebaseapp.com',
    projectId: 'pd-app-f2656',
    storageBucket: 'pd-app-f2656.firebasestorage.app',
    messagingSenderId: '208818382983',
    appId: '1:208818382983:web:69c177f50a804188523022',
    measurementId: 'G-NK0QRX6T3J',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhBNZ-yt9npIdG9hW6X5Z8R6XRcjqTUxc',
    authDomain: 'pd-app-f2656.firebaseapp.com',
    projectId: 'pd-app-f2656',
    storageBucket: 'pd-app-f2656.firebasestorage.app',
    messagingSenderId: '208818382983',
    appId: '1:208818382983:web:69c177f50a804188523022',
    measurementId: 'G-NK0QRX6T3J',
  );
}
